### ISSUE TITLE
❓ [Question] Is the module compiled by TRTorch thread safe?

### ISSUE THREAD

**Issue by uni19** [NVIDIA/Torch-TensorRT#181]
Hi
If the native torchscript module is thread safe when its `forward` function is called from multithread, would the module compiled by TRTorch be thread safe?

**Comment by narendasan** [comment]
That is a good question. We haven't tested for thread safety. If I had to say I would say no, the logger for one is probably not thread safe and the actual execution probably needs to have a lock for inference since TensorRT ExecutionContext is not thread safe in the single module multiple thread case. Even in the multiple module case I think the logger will still cause problems. Can you file an issue to add thread-safety to the runtime?
