### ISSUE TITLE
🐛 [Bug] Dependency node is eliminated if the current segment is a TensorRT segment. 

### ISSUE THREAD

**Issue by peri044** [NVIDIA/Torch-TensorRT#461]
**Is your feature request related to a problem? Please describe.**
Case : 1

```
%0: int aten::__range_length(%1, %2, %3)
%7: Tensor = aten::_convolution(%in)   TensorRT
%8: int[] = listConstrcut(%6, %0) # ?? 
%9: Tensor = aten::maxpool(%7, %8)  TensorRT
```

Segmented block inputs : %in - Tensor , %0 - non tensor

```
graph(%in, %1, %2, %3):
	%0: int aten::__range_length(%1, %2, %3)
    %7: Tensor = aten::_convolution(%in)   TensorRT
    %8: int[] = listConstrcut(%6, %0) # ?? 
    %9: Tensor = aten::maxpool(%7, %8)  TensorRT
```

The dependency node for this segment is %0 which is obtained by `getDependencyNodes` function. But this node is removed from the graph if the segmented block is a tensorrt target. In this example, aten::range_length node is removed which causes unexpected issues.

**Comment by bowang95** [comment]
Hi Dheeraj @peri044  the PR to fix this bug is here: [https://github.com/NVIDIA/TRTorch/pull/462](url)
Also, I pushed the test code for prim if in this branch: [https://github.com/NVIDIA/TRTorch/tree/bowa_primif](url)
Sorry I don't have time to finish the test code for this bug. 
If there is anything wrong you can always contact me. 
Thanks!

**Comment by narendasan** [comment]
@peri044 has this been resolved?

**Comment by peri044** [comment]
Yes, this is fixed
