### ISSUE TITLE
✨[Feature] Support PyTorch <1.10 with Torch-TensorRT release >1.0.0

### ISSUE THREAD

**Issue by chaoz-dev** [NVIDIA/Torch-TensorRT#799]
**Is your feature request related to a problem? Please describe.**
Torch-TensorRT prefers PyTorch 1.10, however, it should be possible to support earlier versions of PyTorch as well (at least >= PyTorch 1.8.1).
Currently, building with PyTorch 1.9 or earlier results in the following build error
```
ERROR: /home/chaoz/workspace/Torch-TensorRT/core/lowering/BUILD:10:11: Compiling core/lowering/register_trt_placeholder_ops.cpp failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
core/lowering/register_trt_placeholder_ops.cpp:16:34: error: invalid user-defined conversion from 'torch::jit::<lambda(torch::jit::Stack&)>' to 'torch::jit::OperationCreator {aka std::function<void(std::vector<c10::IValue>*)> (*)(const torch::jit::Node*)}' [-fpermissive]
         aliasAnalysisFromSchema()),
                                  ^
core/lowering/register_trt_placeholder_ops.cpp:15:24: note: candidate is: torch::jit::<lambda(torch::jit::Stack&)>::operator void (*)(torch::jit::Stack&)() const <near match>
         [](Stack& stack) { /*noop*/ },
                        ^
core/lowering/register_trt_placeholder_ops.cpp:15:24: note:   no known conversion from 'void (*)(torch::jit::Stack&) {aka void (*)(std::vector<c10::IValue>&)}' to 'torch::jit::OperationCreator {aka std::function<void(std::vector<c10::IValue>*)> (*)(const torch::jit::Node*)}'
In file included from external/libtorch_pre_cxx11_abi/include/torch/csrc/jit/runtime/custom_operator.h:5:0,
                 from core/lowering/register_trt_placeholder_ops.cpp:1:
external/libtorch_pre_cxx11_abi/include/torch/csrc/jit/runtime/operator.h:87:3: note:   initializing argument 2 of 'torch::jit::Operator::Operator(std::string, torch::jit::OperationCreator, c10::AliasAnalysisKind)'
   Operator(
   ^~~~~~~~
Target //:libtorchtrt failed to build
```
which is the result of an API change from PyTorch 1.9 -> 1.10, which should be easy to rectify.
Additionally, there are several checks and warnings raised when installing the package with PyTorch <= 1.9 which should not be necessary.

eg. 
```
torch-tensorrt 1.0.0+ea4c5690 requires torch>=1.10.0+cu113<1.11.0, but you have torch 1.9.0+cu111 which is incompatible.                                                                                           
```

**Describe the solution you'd like**
Be able to build and install Torch-TensorRT with PyTorch 1.9 without issues or warnings. 

**Describe alternatives you've considered**
I've tested with PyTorch 1.10 and PyTorch 1.9 with modifications, and it appears that we should be able to support both with few changes? 

**Additional context**

**Comment by chaoz-dev** [comment]
I can put up a PR for the error above, as well as to update the min version supported here. Was there a reason we raised the min version to 1.10 when it appears that the repo is mostly backwards compatible? (And it seems like we expect to be backwards compatible in several places in the code already).

**Comment by narendasan** [comment]
This is a policy thing rather than a technical limitation. In the past there have been significant restructurings of internal apis we depend on which would make supporting multiple versions very difficult in minor releases of PyTorch. Therefore, we only guarantee out of the box compatibility with the current version of PyTorch and update in lockstep with them each quarter so that compatibility expectations are simple to understand: 

- A Torch-TensorRT release is compatible with the latest version of PyTorch out at the time. 

- NGC containers/branches takes the master branch at time of building and makes it compatible with the master branch of PyTorch at time of building (though this is forward looking rather than backwards compatibility).

We have been discussing supporting PyTorch LTS either in a similar LTS release track or through source compatibility in master but IMO that's as far as we should go in terms of supporting multiple PyTorch versions concurrently to keep things simple both for us and users. LTS seems like the most reasonable choice for users who are looking for a stable PyTorch base so it's probably a solid target to maintain compatibility with.

That being said considering each version of Torch-TensorRT has significant feature improvements and bug fixes we are happy to help anyone who is looking to backport current Torch-TensorRT to an older version in their own tree. Just not sure we should be trying to maintain this in master 

cc: @ncomly-nvidia

**Comment by chaoz-dev** [comment]
Ah gotcha, sounds good. Should I still update the above API then, or nah?

**Comment by narendasan** [comment]
Its probably fine for now. Idk if you have any thoughts @ncomly-nvidia

**Comment by chaoz-dev** [comment]
Cool cool, in that case I'll close this ticket until we decide otherwise 👍🏼
